from enum import StrEnum


class Market(StrEnum):
    INDIA = "INDIA"
    UNITED_STATES = "UNITED_STATES"
    JAPAN = "JAPAN"


class SourceTrustTier(StrEnum):
    TIER_1 = "TIER_1"
    TIER_2 = "TIER_2"
    TIER_3 = "TIER_3"
    TIER_4 = "TIER_4"
    TIER_5 = "TIER_5"


class SourceType(StrEnum):
    NEWS = "NEWS"
    FILING = "FILING"
    EARNINGS_CALL = "EARNINGS_CALL"
    TRANSCRIPT = "TRANSCRIPT"
    INTERVIEW = "INTERVIEW"
    SOCIAL_POST = "SOCIAL_POST"
    MACRO_REPORT = "MACRO_REPORT"
    REGULATORY_UPDATE = "REGULATORY_UPDATE"


class EventType(StrEnum):
    EARNINGS_BEAT = "EARNINGS_BEAT"
    EARNINGS_MISS = "EARNINGS_MISS"
    GUIDANCE_UPGRADE = "GUIDANCE_UPGRADE"
    GUIDANCE_DOWNGRADE = "GUIDANCE_DOWNGRADE"
    MERGER = "MERGER"
    DEMERGER = "DEMERGER"
    ACQUISITION = "ACQUISITION"
    MANAGEMENT_CHANGE = "MANAGEMENT_CHANGE"
    BUYBACK = "BUYBACK"
    DIVIDEND = "DIVIDEND"
    CONTRACT_WIN = "CONTRACT_WIN"
    REGULATORY_ACTION = "REGULATORY_ACTION"
    CAPEX = "CAPEX"
    DEBT_ISSUE = "DEBT_ISSUE"
    LITIGATION = "LITIGATION"
    INSIDER_ACTIVITY = "INSIDER_ACTIVITY"
    MACRO_EVENT = "MACRO_EVENT"


class Sentiment(StrEnum):
    POSITIVE = "POSITIVE"
    NEGATIVE = "NEGATIVE"
    NEUTRAL = "NEUTRAL"
    UNCERTAIN = "UNCERTAIN"


class SignalType(StrEnum):
    POSITIVE = "POSITIVE"
    NEGATIVE = "NEGATIVE"
    NEUTRAL = "NEUTRAL"
    UNCERTAIN = "UNCERTAIN"
